import {
  LayoutDashboard,
  Upload,
  Calendar,
  List,
  BarChart,
  Settings,
  Menu,
  X,
  Tv,
  Clock,
  CheckCircle,
  AlertCircle,
  RefreshCw,
  Download,
  Folder,
  FileVideo,
  Users,
  TrendingUp,
  Zap,
  Shield,
  Globe,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Search,
  Filter,
  Plus,
  Minus,
  Edit,
  Trash2,
  Save,
  Copy,
  Move,
  MoreVertical,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  Home,
  User,
  LogOut,
  Bell,
  HelpCircle,
  Info,
  Star,
  Heart,
  Share,
  Link,
  Mail,
  Phone,
  MessageSquare,
  Video,
  VideoOff,
  Mic,
  MicOff,
  Camera,
  CameraOff,
  Volume2,
  VolumeX,
  Pause,
  SkipBack,
  SkipForward,
  Repeat,
  Shuffle,
  Play,
  Square,
  Circle,
  Package,
  Box,
  Archive,
  Database,
  Server,
  Cloud,
  CloudDownload,
  CloudUpload,
  Wifi,
  Activity,
  Brain,
  Sparkles,
  Flame,
  Droplet,
  Wind,
  ZapOff,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Umbrella,
  Gauge,
  Timer,
  AlarmClock,
  Watch,
  CalendarDays,
  CalendarRange,
  CalendarCheck,
  CalendarX,
  CalendarPlus,
  CalendarMinus,
  CalendarSearch,
  CalendarSync,
  CalendarClock,
  PlayCircle,
  Scissors,
  Maximize,
  MessageCircle,
  Tag,
  Check,
  Layers,
  Book,
  Music,
  ZoomIn,
  Edit3,
  ImagePlus,
  Undo,
  Redo,
  Lightbulb,
} from "lucide-react"

export const Icons = {
  layoutDashboard: LayoutDashboard,
  upload: Upload,
  calendar: Calendar,
  list: List,
  barChart: BarChart,
  settings: Settings,
  menu: Menu,
  x: X,
  book:Book,
  playCircle: PlayCircle,
  youtube: Tv,
  clock: Clock,
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  refreshCw: RefreshCw,
  download: Download,
  folder: Folder,
  fileVideo: FileVideo,
  users: Users,
  trendingUp: TrendingUp,
  zap: Zap,
  shield: Shield,
  globe: Globe,
  lock: Lock,
  unlock: Unlock,
  eye: Eye,
  eyeOff: EyeOff,
  search: Search,
  filter: Filter,
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash2: Trash2,
  save: Save,
  copy: Copy,
  move: Move,
  moreVertical: MoreVertical,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  home: Home,
  user: User,
  logOut: LogOut,
  bell: Bell,
  helpCircle: HelpCircle,
  info: Info,
  star: Star,
  heart: Heart,
  share: Share,
  link: Link,
  mail: Mail,
  phone: Phone,
  messageCircle: MessageCircle,
  messageSquare: MessageSquare,
  video: Video,
  videoOff: VideoOff,
  mic: Mic,
  micOff: MicOff,
  camera: Camera,
  cameraOff: CameraOff,
  volume2: Volume2,
  volumeX: VolumeX,
  pause: Pause,
  skipBack: SkipBack,
  skipForward: SkipForward,
  repeat: Repeat,
  shuffle: Shuffle,
  play: Play,
  square: Square,
  circle: Circle,
  package: Package,
  box: Box,
  archive: Archive,
  database: Database,
  server: Server,
  cloud: Cloud,
  cloudDownload: CloudDownload,
  cloudUpload: CloudUpload,
  wifi: Wifi,
  activity: Activity,
  brain: Brain,
  sparkles: Sparkles,
  flame: Flame,
  droplet: Droplet,
  wind: Wind,
  zapOff: ZapOff,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloudLightning: CloudLightning,
  umbrella: Umbrella,
  gauge: Gauge,
  timer: Timer,
  alarmClock: AlarmClock,
  watch: Watch,
  calendarDays: CalendarDays,
  calendarRange: CalendarRange,
  calendarCheck: CalendarCheck,
  calendarX: CalendarX,
  calendarPlus: CalendarPlus,
  calendarMinus: CalendarMinus,
  calendarSearch: CalendarSearch,
  calendarSync: CalendarSync,
  calendarClock: CalendarClock,
  logo: PlayCircle,
  scissors: Scissors,
  maximize: Maximize,
  tag: Tag,
  check: Check,
  layers: Layers,
  music: Music,
  zoomIn: ZoomIn,
  edit3: Edit3,
  imagePlus: ImagePlus,
  undo: Undo,
  redo: Redo,
  lightbulb: Lightbulb,
  google: (props: React.SVGProps<SVGSVGElement>) => (
    <svg
      role="img"
      viewBox="0 0 24 24"
      fill="currentColor"
      xmlns="http://www.w3.org/2000/svg"
      {...props}
    >
      <path d="M12.48 10.92v3.28h7.84c-.24 1.84-.908 3.152-1.928 4.176-1.288 1.288-3.312 2.696-7.84 2.696-7.144 0-12.824-5.784-12.824-12.928s5.68-12.928 12.824-12.928c3.856 0 6.64 1.536 8.752 3.536l2.336-2.336c-2.816-2.656-6.496-4.664-11.088-4.664-9.352 0-17.024 7.672-17.024 17.024s7.672 17.024 17.024 17.024c5.032 0 8.752-1.656 11.696-4.72 2.944-2.944 3.88-7.12 3.88-10.432 0-1.008-.08-1.936-.24-2.736h-15.336z" />
    </svg>
  ),
} as const
